import { useRouter } from 'next/router';
import Head from 'next/head'
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import ColLeft from '../components/ColLeft';
import TableBet from '../components/TableBet'
import Statistics from '../components/Statistics'
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';

const ItemBoards = () => {
    const router = useRouter();
    const { idTable } = router.query;

    const dataBets = [
        {keyBet: "1", date : "2022-01-26", line: "BATMAN VS SUPERMAN", momio: 312312, valueBet: 100000, winBet: 215000, resultBet: 1},
        {keyBet: "2", date : "2022-02-21", line: "TOM VS JERRY", momio: 312312, valueBet: 100000, winBet: 255000, resultBet: 1},
        {keyBet: "3", date : "2022-03-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 235000, resultBet: 1},
        {keyBet: "4", date : "2022-04-26", line: "Steward", momio: 312312, valueBet: 130000, winBet: 212000, resultBet: 1},
        {keyBet: "5", date : "2022-05-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 215000, resultBet: 1},
        {keyBet: "6", date : "2022-06-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 225000, resultBet: 1},
        {keyBet: "7", date : "2022-07-26", line: "Steward", momio: 312312, valueBet: 105000, winBet: 215000, resultBet: 1},
        {keyBet: "8", date : "2022-08-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 265000, resultBet: 1},
        {keyBet: "9", date : "2022-09-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 275000, resultBet: 1},
        {keyBet: "10", date : "2022-10-26", line: "Steward", momio: 312312, valueBet: 130000, winBet: 10000, resultBet: 1},
        {keyBet: "11", date : "2022-11-26", line: "Steward", momio: 312312, valueBet: 100000, winBet: 215000, resultBet: 1},
        {keyBet: "12", date : "2022-12-26", line: "Venus", momio: 312312, valueBet: 100000, winBet: 215000, resultBet: 1},
      ];

    return(
        <div>
            <Head>
              <title>Bet - board {idTable}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
           </Head>
      <Row style={{marginTop: '2rem'}}>
        <Col md={2} className="overflow-hidden">

           <ColLeft idStatis={"DATOS DE LA TABLA"}/>
                
        </Col>
        <Col md={10} className="overflow-auto">
        
        <Tabs
                defaultActiveKey="TableBet"
                id="uncontrolled-tab-example"
                className="mb-3"
                >
                        <Tab eventKey="TableBet" title="TableBet">
                            <TableBet dataTable={idTable} dataBets={dataBets}/>
                        </Tab>
                        <Tab eventKey="statistics" title="Statistics">
                            <Statistics dataBets={dataBets} />
                        </Tab>
                        <Tab eventKey="contact" title="Contact">
                            <div>contact</div>
                        </Tab>  
                </Tabs> 
        
        </Col>
      </Row>

            

        </div>
    );
}

export default ItemBoards;