import { useRouter } from 'next/router';
import Head from 'next/head'
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import ColLeft from '../components/ColLeft';
import TableBet from '../components/TableBet'
import Statistics from '../components/Statistics'
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';

const ItemBoards = () => {
    const router = useRouter();
    const { idTable } = router.query;
    return(
        <div>
            <Head>
              <title>Bet - board {idTable}</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
           </Head>
      <Row>
        <Col md={2} className="overflow-hidden">
        <br></br>
           <ColLeft idStatis={idTable}/>
                
        </Col>
        <Col md={10} style={{marginTop: '2rem'}} className="overflow-auto">
        
        <Tabs
                defaultActiveKey="TableBet"
                id="uncontrolled-tab-example"
                className="mb-3"
                >
                        <Tab eventKey="TableBet" title="TableBet">
                            <TableBet />
                        </Tab>
                        <Tab eventKey="statistics" title="Statistics">
                            <Statistics />
                        </Tab>
                        <Tab eventKey="contact" title="Contact">
                            <div>contact</div>
                        </Tab>  
                </Tabs> 
        
        </Col>
      </Row>

            

        </div>
    );
}

export default ItemBoards;