import { useRouter } from 'next/router'
import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';
import Image from 'next/image'
import logo from '../public/LOGO APUESTAS 1.svg'



export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Apuestas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Container>
      <Row className="justify-content-md-center">
          <Col style={{
            marginTop: "15rem",
        }}>
               <h2>CONTROL TOTAL</h2>
               <h1>DE TODAS TUS APUESTAS</h1>
               <Button variant="outline-dark" onClick={() => router.push('/dashboard')}>DESCUBRELO</Button>
          </Col>
          <Col style={{
            marginTop: "3rem",


        }}>
          <Image
              alt=""
              src={logo}
              width="500"
              height="500"
              className="d-inline-block align-top"
            />
          </Col>
      </Row>
      </Container>
</>
  )
}
